language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "6"
env:
  global:
    - DETAILED=false
  matrix:
    - DETAILED=true
matrix:
  include:
    - node_js: "4"
      env:
    - node_js: "5"
      env:
    - node_js: "7"
      env:
addons:
  sonarqube:
    token:
      secure: "$SECURE_TOKEN_SONARQUBE"
    github_token:
      secure: "$SECURE_TOKEN_GITHUB"
  branches:
    - master
before_install:
  - rm -rf ~/.linuxbrew
  - yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
  - brew install jdk
  - export JAVA_HOME=/home/travis/.linuxbrew/Cellar/jdk/1.8.0-112
before_script:
  - npm prune
script:
  - npm run eslint
  - npm run build
  - npm run coverage
  - npm run test-npm-package
  - "[ $DETAILED == false ] || [ $TRAVIS_PULL_REQUEST == true] || npm run test-sl || true"
after_success:
  - "[ $DETAILED == false ] || [ $TRAVIS_PULL_REQUEST == true] || npm run report-coverage"
  - sonar-scanner