language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "6"
env:
  global:
    - DETAILED=false
  matrix:
    - DETAILED=true
matrix:
  include:
    - node_js: "4"
      env:
    - node_js: "5"
      env:
    - node_js: "7"
      env:
addons:
  sonarqube:
    token:
      secure: "pMggT48hITF1Hd/ouNFXeBzwOdeZunO2x17SPA1k7/1e12NNYanzaQsEJURAkKAfexxgFUxU55UVjYMoMrfOBoM+DwkVP653JTzV2VmhF7R61vnxpTJzeW1FFKfKPReL2EPGyvQbBx07eujI+Fxa+1yd2iv+zoSYe4SBHPdz5IUMo8CbpRW/l7sZ9ZpDsj2ZPyZjDmEb8yYDKMOczsRfyPt98k9kwIcxtzaLpegF9WWc0LklGslm1hgvlpuB5cm0RWTmwCid7ZHZBueIqDxMYVOnTkFgK6O3cX+6C6t7KGlytBIzzs1IbmNtD2kdWiGN/h4ggKl1ggS3MzhOwDBQpjzJqqMARGRnFUUfztrXBLtDUbtwkrivqDuqBqTBm8ga0bgvQqeFclXkTijIDy68aW9p7sBZiRh+vwtEJr7n36puKGWGTan/bQPnO1MdeE847SqXd6EY/BaHZ5VFzVxlq5YVd0RSLD+40trxSbAwB8TeB7txE95dwtsHynMGTo8O2X5Y84tXYcx/I+uEz7UfcCAeCHu+uYQOUHENgxFyRVKKqPQjtqvFxQI9u2kGS9+6+nm1s7jRxXqieb15vSEWOtU01IW0Ve1NcXd2geIEWuDhcQO9ySTPSFlJI9Kv2dyjV3edVsjV5FWHRaVWo2gUgxdoxlF9/69+vxptmBsLRXg="
    github_token:
      secure: "tgVGUOc33So1RSaHeHTBsf0U3mZHRet3UubTjHj0NIkKxGP6HfyTwMfpM02c7dvn5uqNSO9/BX4nCimVx3v1edut3fhpsxQBfIwRyOe+hUmkYu2wN7ICZIdzN7Wlj4BTe+XF1wsHxs545AX/lBjLHA3flLGCiqPDz3hKuGw2mt6al/MsikxxNI1BHsN5OC6Gvsav20MLgclYLU8XgZk/2gnMOOdnVG3C5ve8hFlNa7cO0kdsdHTEgP0tofgmWCq/sTYRO0dnxurU+1rlsa/fgJWtgwKJW72dtT707NCyNfGJzsBk1Yv+lkyGVykl+pOjHSVan005K7F6Bk1D50fwX9eGnNgxtrl/Cx+Ax+sj9DTLr59b4VU1BwRXhBfZQxdHYjGzE43e8immit77MFNqzc35UES5GcuBo2QSczbuxYeaBcwdZRdVHWGXsuRM5soSnUNK6REuX3lQOKpZhY+5EVCHcsVzPn6KBSR+5yBvoC1b1GIarHCIh3K4cLMDQY5qjEDqwITQCwJ49YAoc1JVqKnB/jr69Np/Wk+IDGtzRC4KWvSPR5VGw1uZ3uYAv9OTb4qoiw+USwLOTp2+XbJtiwsvRIAH6RIS+kMbwadWm3QIDeGNf4CfnuarXvHKVWPshk0pKEvcrJnOQcbVFsyebEHI52EKwLGJwAT/AQ3+euE="
  branches:
    - master
before_install:
  - rm -rf ~/.linuxbrew
  - yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
  - brew install jdk
  - export JAVA_HOME=/home/travis/.linuxbrew/Cellar/jdk/1.8.0-112
before_script:
  - npm prune
script:
  - npm run eslint
  - npm run build
  - npm run coverage
  - npm run test-npm-package
  - "[ $DETAILED == false ] || [ $TRAVIS_PULL_REQUEST == true] || npm run test-sl || true"
  - sonar-scanner
after_success:
  - "[ $DETAILED == false ] || [ $TRAVIS_PULL_REQUEST == true] || npm run report-coverage"